[workspace]
projects = ["GenerateLinext", "GenerateWeakOrder", "GenerateWeakOrderExt"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
