margin = 88
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = true
short_to_long_function_def = true
long_to_short_function_def = true
always_use_return = true
format_docstrings = true
conditional_to_if = true
indent_submodule = true
separate_kwargs_with_semicolon = true
for_in_replacement = "∈"
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true
