FIELDNAMES = {
    "train_results": [
        "M",
        "N_tr",
        "Atr_id",
        "Mo",
        "Ko",
        "Group_size",
        "Group_id",
        "N_bc",
        "Error",
        "D_id",
        "Me",
        "Ke",
        "Method",
        "Config",
        "Me_id",
        "Time",
        "Fitness",
        "It.",
    ],
    "test_results": [
        "M",
        "N_tr",
        "Atr_id",
        "Mo",
        "Ko",
        "Group_size",
        "Group_id",
        "N_bc",
        "Error",
        "D_id",
        "Me",
        "Ke",
        "Method",
        "Config",
        "Me_id",
        "N_te",
        "Ate_id",
        "Fitness",
        "Kendall's tau",
    ],
    "configs": ["Id", "Method", "Config"],
    "seeds": ["Task", "Seed"],
}
